seed: 1234
val_dataset: "planning-datasets/val/"
dataset: "planning-datasets/mpd/instances/032/"
logdir: "model/h"
map_type: "bmap"
Tmax: 0.25
logpath: "logs" 

encoder:
  input: 3
  arch: "UNet"
  depth: 4

params:
  training: True
  batch_size: 100
  num_epochs: 200
  lr: 0.00025
  gpu_id: 0
  w_decay: 0.001
  factor: 0.1
  min_lr: 0.0000001
  patience: 4
  map_num: 80


hydra:
  job:
    chdir: False

modelConfig:
  model-save: model

